name: cluautils workflow

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.0.0"

      - name: build
        run: |
          luarocks make

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: "3.0.0"
      - name: publish-luarocks
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        run: |
          git config --global url."https://".insteadOf git://
          luarocks install --local dkjson
          luarocks upload cluautils-*.rockspec --api-key=$LUAROCKS_API_KEY --force
