name: cluautils workflow       
on:
  push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: xpol/setup-lua@v1
        with:
          lua-version: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v2
        with:
          luarocksVersion: "3.0.0"
      
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: build
        run: sudo luarocks make
